### ISSUE TITLE
Hello, I want to reproduce the Fig. S7 in the supplemental materials.

### ISSUE THREAD

**Issue by BaldStrong** [pjzuk/RepulsionSData#1]
Hello, I want to reproduce the Fig. S7 in the supplemental materials. 
![image](https://user-images.githubusercontent.com/37842039/153751085-2d3d1aa8-f67c-48ee-8dec-c246ba42143c.png)
I ran _oneDimCase_ and got _nPlus_ and _nMinus_ for each moment at position 0, then added them up and averaged them, and finally took log10, but the results are far from yours, and I don't know if I'm doing it right, and would really appreciate your help!

**Comment by pjzuk** [comment]
Hi, I hope we figure that out. 
How long have you waited before "recording" the oscillation period for time averaging? I mean, the system requires an order of L^2/D_{slow ions} time to relax the ions from the bulk. Before you record not a steady state. If this does not help, please let me know.

**Comment by BaldStrong** [comment]
Thank you very much for your help, I'll elaborate on how I got these points and have run them for enough time, but the results are still not good.
![image](https://user-images.githubusercontent.com/37842039/153759698-cfba7b0b-d4d7-42b0-9b68-0fbedc933096.png)

Each nPlus value is taken from . /oneDimCase/$time/nPlus from the first of 9000 values.

Here's the excel file above:
[data.xlsx](https://github.com/pjzuk/RepulsionSData/files/8055785/data.xlsx)

**Comment by pjzuk** [comment]
Hi again,
so I just checked, that everything should be fine upon some patience. Let's go:
1) we take the example from gitRepo as is: NaNO3, 1mM, 1e5Hz 70mV forcing
2) I calculated as is until time t=0.002
3) There is a probe feature in OpenFOAM, which I added to the system/controlDict file to get the data:
 functions
(
    probes
    {
        type            probes;
        functionObjectLibs ("libsampling.so");
        enabled         true;
        outputControl   outputTime;
        outputInterval  1;
        probeLocations
        (
            ( 0.    5e-8 5e-8 )
            ( 1e-11 5e-8 5e-8 )
            ( 1e-7  5e-8 5e-8 )
        );

        fields
        (
            nPlus
            nMinus
            ePhi
        );
    }
);
this will give you probes folder including field values.
4) I set the time to fixed time step 2e-10, write interval 5e-8 and endTime to 2.01e-3
5) I run the simulation to get 200 data points, which look similar to yours. Therefore, I expect is is fine up to this point.
6) Now I calculate the average of nPlus at x=0 (from probes/0.001/nPlus), which I got to be <n+> \approx 1.41
7) Then I calcuate what we need:
<n+> = (1 + n+^(0) * V^2 + ....) 
n+^(0) * V^2 = <n+>  - 1 = 0.41
n+^(0) =/ V^2 = /2.7^2 \approx 0.056 
similarly for n-^(0) \approx .058
so we get log10(n+^(0)+n-^(0)) \ approx -0.94
8) We are at n0 = 6.022e+23 particles per m^3 which is 1 mM, log10(n0/mM) = 0 
9) This is quite close to what is in the fig S7 a)
9) I checked 0.001 and 0.002 and it seems that it has converged quite well. I think I waited until 0.01 but it has been some time now and I do not remember all the details.
10) Beware that this is a very subtle system which means that number of averaging points and equilibration time will have some influence on the final calculations.

**Comment by BaldStrong** [comment]
I am very impressed with your rigorous and patient guidance, the problem has been solved, but I would also like to draw a distribution of cation concentration with time position, can I just use the values in _oneDimCase/$time/nPlus_ to represent the cation concentration?
Finally, thank you again for your great help!

**Comment by pjzuk** [comment]
Hi again,
sure you can. But beware that the mesh is not uniform and that you need to identify the x coordinate of given cell correctly. This is why I have showed you the probes utility. There should be also a similar one to calculate the averages of the complete fields, but I have never used it. Instead I write my own utilities for post processing.
good luck!
